"""Initial Migration.

Revision ID: cefaf5b1dd42
Revises: 
Create Date: 2024-03-11 01:19:53.100976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cefaf5b1dd42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('life_points', sa.Integer(), nullable=True),
    sa.Column('photo_id', sa.String(length=100), nullable=True),
    sa.Column('experience_points', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('player_id', sa.String(length=100), nullable=True),
    sa.Column('card_slot_1', sa.Integer(), nullable=True),
    sa.Column('card_slot_2', sa.Integer(), nullable=True),
    sa.Column('card_slot_3', sa.Integer(), nullable=True),
    sa.Column('card_slot_4', sa.Integer(), nullable=True),
    sa.Column('card_slot_5', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ability')
    op.drop_table('player')
    op.drop_table('character')
    # ### end Alembic commands ###
